// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_1d_cl_array_array_ap_fixed_16u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_V_TDATA,
        data_V_data_V_TVALID,
        data_V_data_V_TREADY,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write,
        res_V_data_8_V_din,
        res_V_data_8_V_full_n,
        res_V_data_8_V_write,
        res_V_data_9_V_din,
        res_V_data_9_V_full_n,
        res_V_data_9_V_write,
        res_V_data_10_V_din,
        res_V_data_10_V_full_n,
        res_V_data_10_V_write,
        res_V_data_11_V_din,
        res_V_data_11_V_full_n,
        res_V_data_11_V_write,
        res_V_data_12_V_din,
        res_V_data_12_V_full_n,
        res_V_data_12_V_write,
        res_V_data_13_V_din,
        res_V_data_13_V_full_n,
        res_V_data_13_V_write,
        res_V_data_14_V_din,
        res_V_data_14_V_full_n,
        res_V_data_14_V_write,
        res_V_data_15_V_din,
        res_V_data_15_V_full_n,
        res_V_data_15_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state11 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_data_V_TDATA;
input   data_V_data_V_TVALID;
output   data_V_data_V_TREADY;
output  [15:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [15:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [15:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [15:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [15:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [15:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [15:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [15:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;
output  [15:0] res_V_data_8_V_din;
input   res_V_data_8_V_full_n;
output   res_V_data_8_V_write;
output  [15:0] res_V_data_9_V_din;
input   res_V_data_9_V_full_n;
output   res_V_data_9_V_write;
output  [15:0] res_V_data_10_V_din;
input   res_V_data_10_V_full_n;
output   res_V_data_10_V_write;
output  [15:0] res_V_data_11_V_din;
input   res_V_data_11_V_full_n;
output   res_V_data_11_V_write;
output  [15:0] res_V_data_12_V_din;
input   res_V_data_12_V_full_n;
output   res_V_data_12_V_write;
output  [15:0] res_V_data_13_V_din;
input   res_V_data_13_V_full_n;
output   res_V_data_13_V_write;
output  [15:0] res_V_data_14_V_din;
input   res_V_data_14_V_full_n;
output   res_V_data_14_V_write;
output  [15:0] res_V_data_15_V_din;
input   res_V_data_15_V_full_n;
output   res_V_data_15_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_V_TREADY;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;
reg res_V_data_8_V_write;
reg res_V_data_9_V_write;
reg res_V_data_10_V_write;
reg res_V_data_11_V_write;
reg res_V_data_12_V_write;
reg res_V_data_13_V_write;
reg res_V_data_14_V_write;
reg res_V_data_15_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [3:0] outidx_address0;
reg    outidx_ce0;
wire   [1:0] outidx_q0;
wire   [3:0] w2_V_address0;
reg    w2_V_ce0;
wire   [57:0] w2_V_q0;
reg    data_V_data_V_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg    res_V_data_0_V_blk_n;
wire    ap_CS_fsm_state11;
reg   [0:0] p_Result_s_reg_1644;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg    res_V_data_8_V_blk_n;
reg    res_V_data_9_V_blk_n;
reg    res_V_data_10_V_blk_n;
reg    res_V_data_11_V_blk_n;
reg    res_V_data_12_V_blk_n;
reg    res_V_data_13_V_blk_n;
reg    res_V_data_14_V_blk_n;
reg    res_V_data_15_V_blk_n;
reg   [3:0] w_index50_reg_584;
reg   [31:0] in_index_0_i_i_i_i_i49_reg_595;
reg   [15:0] tmp_data_0_V_1148_reg_607;
reg   [15:0] tmp_data_1_V_846_reg_618;
reg   [15:0] tmp_data_2_V_844_reg_629;
reg   [15:0] tmp_data_3_V_842_reg_640;
reg   [15:0] tmp_data_4_V_840_reg_651;
reg   [15:0] tmp_data_5_V_838_reg_662;
reg   [15:0] tmp_data_6_V_836_reg_673;
reg   [15:0] tmp_data_7_V_834_reg_684;
reg   [15:0] tmp_data_8_V_832_reg_695;
reg   [15:0] tmp_data_9_V_830_reg_706;
reg   [15:0] tmp_data_10_V_828_reg_717;
reg   [15:0] tmp_data_11_V_826_reg_728;
reg   [15:0] tmp_data_12_V_824_reg_739;
reg   [15:0] tmp_data_13_V_822_reg_750;
reg   [15:0] tmp_data_14_V_820_reg_761;
reg   [15:0] tmp_data_15_V_818_reg_772;
reg   [15:0] tmp_data_3_V_reg_783;
reg   [15:0] tmp_data_2_V_reg_802;
reg   [15:0] tmp_data_1_V_reg_821;
reg   [15:0] tmp_data_0_V_reg_840;
reg   [15:0] tmp_data_7_V_reg_859;
reg   [15:0] tmp_data_6_V_reg_878;
reg   [15:0] tmp_data_5_V_reg_897;
reg   [15:0] tmp_data_4_V_reg_916;
reg   [15:0] tmp_data_11_V_reg_935;
reg   [15:0] tmp_data_10_V_reg_954;
reg   [15:0] tmp_data_9_V_reg_973;
reg   [15:0] tmp_data_8_V_reg_992;
reg   [15:0] tmp_data_15_V_reg_1011;
reg   [15:0] tmp_data_14_V_reg_1030;
reg   [15:0] tmp_data_13_V_reg_1049;
reg   [15:0] tmp_data_12_V_reg_1068;
wire   [0:0] icmp_ln20_fu_1091_p2;
reg   [0:0] icmp_ln20_reg_1614;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln26_fu_1097_p2;
reg   [0:0] icmp_ln26_reg_1620;
wire   [2:0] select_ln31_fu_1161_p3;
reg   [2:0] select_ln31_reg_1625;
wire   [7:0] i_iw_fu_1225_p2;
reg   [7:0] i_iw_reg_1633;
wire    data_window_0_V_V_full_n;
reg    data_window_0_V_V_write;
wire   [0:0] trunc_ln13_fu_1221_p1;
wire    data_window_1_V_V_full_n;
reg    data_window_1_V_V_write;
wire   [0:0] tmp_1320_fu_1231_p3;
wire    data_window_2_V_V_full_n;
reg    data_window_2_V_V_write;
wire   [0:0] tmp_1321_fu_1239_p3;
reg    ap_block_state3;
wire   [0:0] p_Result_s_fu_1247_p3;
reg   [15:0] tmp_V_reg_1648;
wire    ap_CS_fsm_state4;
wire   [15:0] data_window_0_V_V_dout;
wire    data_window_0_V_V_empty_n;
reg    data_window_0_V_V_read;
wire   [15:0] data_window_1_V_V_dout;
wire    data_window_1_V_V_empty_n;
reg    data_window_1_V_V_read;
wire   [15:0] data_window_2_V_V_dout;
wire    data_window_2_V_V_empty_n;
reg    data_window_2_V_V_read;
reg    ap_block_state4;
reg   [15:0] tmp_V_1024_reg_1653;
reg   [15:0] tmp_V_1025_reg_1658;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state10_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] w_index_fu_1261_p2;
reg   [3:0] w_index_reg_1673;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] in_index_fu_1267_p2;
reg   [31:0] in_index_reg_1678;
wire   [0:0] icmp_ln168_fu_1273_p2;
reg   [0:0] icmp_ln168_reg_1683;
wire   [0:0] icmp_ln151_fu_1279_p2;
reg   [0:0] icmp_ln151_reg_1688;
reg   [0:0] icmp_ln151_reg_1688_pp0_iter1_reg;
reg   [0:0] icmp_ln151_reg_1688_pp0_iter2_reg;
reg   [0:0] icmp_ln151_reg_1688_pp0_iter3_reg;
reg   [0:0] icmp_ln151_reg_1688_pp0_iter4_reg;
reg   [1:0] out_index_reg_1692;
reg   [1:0] out_index_reg_1692_pp0_iter2_reg;
reg   [1:0] out_index_reg_1692_pp0_iter3_reg;
reg   [1:0] out_index_reg_1692_pp0_iter4_reg;
wire   [15:0] tmp_1155_fu_1289_p5;
reg   [15:0] tmp_1155_reg_1699;
wire   [15:0] trunc_ln160_1_fu_1298_p1;
reg  signed [15:0] trunc_ln160_1_reg_1704;
reg  signed [15:0] tmp_1156_reg_1709;
reg  signed [15:0] tmp_1157_reg_1714;
reg  signed [9:0] tmp_1158_reg_1719;
wire   [31:0] select_ln168_fu_1332_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [25:0] sext_ln1116_cast_fu_1338_p1;
wire  signed [25:0] grp_fu_1572_p2;
reg  signed [25:0] mul_ln1118_reg_1757;
wire  signed [25:0] grp_fu_1578_p2;
reg  signed [25:0] mul_ln1118_1155_reg_1762;
wire  signed [25:0] grp_fu_1584_p2;
reg  signed [25:0] mul_ln1118_1156_reg_1767;
wire  signed [25:0] grp_fu_1590_p2;
reg  signed [25:0] mul_ln1118_1157_reg_1772;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg   [7:0] wp_idx51_reg_572;
reg    ap_block_state1;
wire    io_acc_block_signal_op190;
reg    ap_block_state11;
wire   [0:0] icmp_ln49_fu_1566_p2;
reg   [3:0] ap_phi_mux_w_index50_phi_fu_588_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_in_index_0_i_i_i_i_i49_phi_fu_599_p4;
reg   [15:0] ap_phi_mux_tmp_data_0_V_phi_fu_845_p8;
reg   [15:0] ap_phi_mux_tmp_data_1_V_phi_fu_826_p8;
reg   [15:0] ap_phi_mux_tmp_data_2_V_phi_fu_807_p8;
reg   [15:0] ap_phi_mux_tmp_data_3_V_phi_fu_788_p8;
reg   [15:0] ap_phi_mux_tmp_data_4_V_phi_fu_921_p8;
reg   [15:0] ap_phi_mux_tmp_data_5_V_phi_fu_902_p8;
reg   [15:0] ap_phi_mux_tmp_data_6_V_phi_fu_883_p8;
reg   [15:0] ap_phi_mux_tmp_data_7_V_phi_fu_864_p8;
reg   [15:0] ap_phi_mux_tmp_data_8_V_phi_fu_997_p8;
reg   [15:0] ap_phi_mux_tmp_data_9_V_phi_fu_978_p8;
reg   [15:0] ap_phi_mux_tmp_data_10_V_phi_fu_959_p8;
reg   [15:0] ap_phi_mux_tmp_data_11_V_phi_fu_940_p8;
reg   [15:0] ap_phi_mux_tmp_data_12_V_phi_fu_1073_p8;
reg   [15:0] ap_phi_mux_tmp_data_13_V_phi_fu_1054_p8;
reg   [15:0] ap_phi_mux_tmp_data_14_V_phi_fu_1035_p8;
reg   [15:0] ap_phi_mux_tmp_data_15_V_phi_fu_1016_p8;
wire   [15:0] acc_0_V_fu_1378_p2;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_3_V_reg_783;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_2_V_reg_802;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_1_V_reg_821;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_0_V_reg_840;
wire   [15:0] acc_4_V_fu_1435_p2;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_7_V_reg_859;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_6_V_reg_878;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_5_V_reg_897;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_4_V_reg_916;
wire   [15:0] acc_8_V_fu_1499_p2;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_11_V_reg_935;
wire   [3:0] or_ln_fu_1454_p3;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_10_V_reg_954;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_9_V_reg_973;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_8_V_reg_992;
wire   [15:0] acc_12_V_fu_1556_p2;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_15_V_reg_1011;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_14_V_reg_1030;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_13_V_reg_1049;
wire   [15:0] ap_phi_reg_pp0_iter5_tmp_data_12_V_reg_1068;
wire   [63:0] zext_ln155_fu_1255_p1;
wire   [7:0] r_fu_1103_p2;
wire   [6:0] tmp_1319_fu_1109_p4;
wire   [0:0] trunc_ln49_fu_1087_p1;
wire   [0:0] or_ln26_fu_1137_p2;
wire   [0:0] icmp_ln31_fu_1119_p2;
wire   [0:0] xor_ln26_fu_1143_p2;
wire   [2:0] trunc_ln32_fu_1125_p1;
wire   [0:0] and_ln31_fu_1149_p2;
wire   [2:0] sub_ln31_fu_1155_p2;
wire   [2:0] select_ln35_fu_1129_p3;
wire   [0:0] xor_ln20_fu_1169_p2;
wire   [0:0] and_ln26_fu_1174_p2;
wire   [0:0] or_ln321_fu_1187_p2;
wire   [2:0] select_ln321_fu_1179_p3;
wire   [2:0] p_Val2_s_fu_1199_p9;
wire   [2:0] p_Val2_s_fu_1199_p10;
wire   [1:0] tmp_1155_fu_1289_p4;
wire   [15:0] trunc_ln_fu_1353_p4;
wire   [15:0] phi_ln_fu_1365_p6;
wire   [3:0] zext_ln1265_fu_1362_p1;
wire   [15:0] phi_ln1265_1_fu_1397_p18;
wire   [15:0] trunc_ln708_1155_fu_1388_p4;
wire   [3:0] phi_ln1265_2_fu_1461_p17;
wire   [15:0] phi_ln1265_2_fu_1461_p18;
wire   [15:0] trunc_ln708_1156_fu_1445_p4;
wire   [15:0] phi_ln1265_3_fu_1518_p18;
wire   [15:0] trunc_ln708_1157_fu_1509_p4;
wire  signed [15:0] grp_fu_1572_p1;
wire  signed [15:0] grp_fu_1578_p0;
wire  signed [15:0] grp_fu_1584_p0;
wire  signed [15:0] grp_fu_1590_p0;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_data_V_data_V_U_apdone_blk;
wire   [15:0] data_V_data_V_TDATA_int;
wire    data_V_data_V_TVALID_int;
reg    data_V_data_V_TREADY_int;
wire    regslice_both_data_V_data_V_U_ack_in;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

conv_1d_cl_array_array_ap_fixed_16u_config2_s_outidx #(
    .DataWidth( 2 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

conv_1d_cl_array_array_ap_fixed_16u_config2_s_w2_V #(
    .DataWidth( 58 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

myproject_mux_83_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
myproject_mux_83_3_1_1_U3(
    .din0(3'd1),
    .din1(3'd2),
    .din2(3'd5),
    .din3(3'd2),
    .din4(3'd4),
    .din5(3'd0),
    .din6(3'd0),
    .din7(3'd0),
    .din8(p_Val2_s_fu_1199_p9),
    .dout(p_Val2_s_fu_1199_p10)
);

myproject_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_32_16_1_1_U4(
    .din0(tmp_V_reg_1648),
    .din1(tmp_V_1024_reg_1653),
    .din2(tmp_V_1025_reg_1658),
    .din3(tmp_1155_fu_1289_p4),
    .dout(tmp_1155_fu_1289_p5)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U5(
    .din0(tmp_data_0_V_1148_reg_607),
    .din1(tmp_data_1_V_846_reg_618),
    .din2(tmp_data_2_V_844_reg_629),
    .din3(tmp_data_3_V_842_reg_640),
    .din4(out_index_reg_1692_pp0_iter4_reg),
    .dout(phi_ln_fu_1365_p6)
);

myproject_mux_164_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
myproject_mux_164_16_1_1_U6(
    .din0(tmp_data_4_V_840_reg_651),
    .din1(tmp_data_5_V_838_reg_662),
    .din2(tmp_data_6_V_836_reg_673),
    .din3(tmp_data_7_V_834_reg_684),
    .din4(tmp_data_7_V_834_reg_684),
    .din5(tmp_data_7_V_834_reg_684),
    .din6(tmp_data_7_V_834_reg_684),
    .din7(tmp_data_7_V_834_reg_684),
    .din8(tmp_data_7_V_834_reg_684),
    .din9(tmp_data_7_V_834_reg_684),
    .din10(tmp_data_7_V_834_reg_684),
    .din11(tmp_data_7_V_834_reg_684),
    .din12(tmp_data_7_V_834_reg_684),
    .din13(tmp_data_7_V_834_reg_684),
    .din14(tmp_data_7_V_834_reg_684),
    .din15(tmp_data_7_V_834_reg_684),
    .din16(zext_ln1265_fu_1362_p1),
    .dout(phi_ln1265_1_fu_1397_p18)
);

myproject_mux_164_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
myproject_mux_164_16_1_1_U7(
    .din0(tmp_data_11_V_826_reg_728),
    .din1(tmp_data_11_V_826_reg_728),
    .din2(tmp_data_11_V_826_reg_728),
    .din3(tmp_data_11_V_826_reg_728),
    .din4(tmp_data_11_V_826_reg_728),
    .din5(tmp_data_11_V_826_reg_728),
    .din6(tmp_data_11_V_826_reg_728),
    .din7(tmp_data_11_V_826_reg_728),
    .din8(tmp_data_8_V_832_reg_695),
    .din9(tmp_data_9_V_830_reg_706),
    .din10(tmp_data_10_V_828_reg_717),
    .din11(tmp_data_11_V_826_reg_728),
    .din12(tmp_data_11_V_826_reg_728),
    .din13(tmp_data_11_V_826_reg_728),
    .din14(tmp_data_11_V_826_reg_728),
    .din15(tmp_data_11_V_826_reg_728),
    .din16(phi_ln1265_2_fu_1461_p17),
    .dout(phi_ln1265_2_fu_1461_p18)
);

myproject_mux_164_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
myproject_mux_164_16_1_1_U8(
    .din0(tmp_data_12_V_824_reg_739),
    .din1(tmp_data_13_V_822_reg_750),
    .din2(tmp_data_14_V_820_reg_761),
    .din3(tmp_data_15_V_818_reg_772),
    .din4(tmp_data_15_V_818_reg_772),
    .din5(tmp_data_15_V_818_reg_772),
    .din6(tmp_data_15_V_818_reg_772),
    .din7(tmp_data_15_V_818_reg_772),
    .din8(tmp_data_15_V_818_reg_772),
    .din9(tmp_data_15_V_818_reg_772),
    .din10(tmp_data_15_V_818_reg_772),
    .din11(tmp_data_15_V_818_reg_772),
    .din12(tmp_data_15_V_818_reg_772),
    .din13(tmp_data_15_V_818_reg_772),
    .din14(tmp_data_15_V_818_reg_772),
    .din15(tmp_data_15_V_818_reg_772),
    .din16(zext_ln1265_fu_1362_p1),
    .dout(phi_ln1265_3_fu_1518_p18)
);

myproject_mul_mul_16s_16s_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_3_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln160_1_reg_1704),
    .din1(grp_fu_1572_p1),
    .ce(1'b1),
    .dout(grp_fu_1572_p2)
);

myproject_mul_mul_16s_16s_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_3_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1578_p0),
    .din1(tmp_1156_reg_1709),
    .ce(1'b1),
    .dout(grp_fu_1578_p2)
);

myproject_mul_mul_16s_16s_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_3_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1584_p0),
    .din1(tmp_1157_reg_1714),
    .ce(1'b1),
    .dout(grp_fu_1584_p2)
);

myproject_mul_mul_16s_10s_26_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_10s_26_3_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1590_p0),
    .din1(tmp_1158_reg_1719),
    .ce(1'b1),
    .dout(grp_fu_1590_p2)
);

fifo_w16_d99_A data_window_0_V_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_V_data_V_TDATA_int),
    .if_full_n(data_window_0_V_V_full_n),
    .if_write(data_window_0_V_V_write),
    .if_dout(data_window_0_V_V_dout),
    .if_empty_n(data_window_0_V_V_empty_n),
    .if_read(data_window_0_V_V_read)
);

fifo_w16_d99_A data_window_1_V_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_V_data_V_TDATA_int),
    .if_full_n(data_window_1_V_V_full_n),
    .if_write(data_window_1_V_V_write),
    .if_dout(data_window_1_V_V_dout),
    .if_empty_n(data_window_1_V_V_empty_n),
    .if_read(data_window_1_V_V_read)
);

fifo_w16_d99_A data_window_2_V_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_V_data_V_TDATA_int),
    .if_full_n(data_window_2_V_V_full_n),
    .if_write(data_window_2_V_V_write),
    .if_dout(data_window_2_V_V_dout),
    .if_empty_n(data_window_2_V_V_empty_n),
    .if_read(data_window_2_V_V_read)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_V_data_V_TDATA),
    .vld_in(data_V_data_V_TVALID),
    .ack_in(regslice_both_data_V_data_V_U_ack_in),
    .data_out(data_V_data_V_TDATA_int),
    .vld_out(data_V_data_V_TVALID_int),
    .ack_out(data_V_data_V_TREADY_int),
    .apdone_blk(regslice_both_data_V_data_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln49_fu_1566_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln151_fu_1279_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_0_i_i_i_i_i49_reg_595 <= select_ln168_fu_1332_p3;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index_0_i_i_i_i_i49_reg_595 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_0_V_1148_reg_607 <= ap_phi_mux_tmp_data_0_V_phi_fu_845_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_0_V_1148_reg_607 <= 16'd123;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_0_V_reg_840 <= acc_0_V_fu_1378_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_0_V_reg_840 <= tmp_data_0_V_1148_reg_607;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_0_V_reg_840 <= ap_phi_reg_pp0_iter5_tmp_data_0_V_reg_840;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_10_V_828_reg_717 <= ap_phi_mux_tmp_data_10_V_phi_fu_959_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_10_V_828_reg_717 <= 16'd65517;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln_fu_1454_p3 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_10_V_reg_954 <= acc_8_V_fu_1499_p2;
    end else if ((((or_ln_fu_1454_p3 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_10_V_reg_954 <= tmp_data_10_V_828_reg_717;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_10_V_reg_954 <= ap_phi_reg_pp0_iter5_tmp_data_10_V_reg_954;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_11_V_826_reg_728 <= ap_phi_mux_tmp_data_11_V_phi_fu_940_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_11_V_826_reg_728 <= 16'd65464;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_ln_fu_1454_p3 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((or_ln_fu_1454_p3 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_11_V_reg_935 <= tmp_data_11_V_826_reg_728;
    end else if ((~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_11_V_reg_935 <= acc_8_V_fu_1499_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_11_V_reg_935 <= ap_phi_reg_pp0_iter5_tmp_data_11_V_reg_935;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_12_V_824_reg_739 <= ap_phi_mux_tmp_data_12_V_phi_fu_1073_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_12_V_824_reg_739 <= 16'd65469;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_12_V_reg_1068 <= acc_12_V_fu_1556_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_12_V_reg_1068 <= tmp_data_12_V_824_reg_739;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_12_V_reg_1068 <= ap_phi_reg_pp0_iter5_tmp_data_12_V_reg_1068;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_13_V_822_reg_750 <= ap_phi_mux_tmp_data_13_V_phi_fu_1054_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_13_V_822_reg_750 <= 16'd133;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_13_V_reg_1049 <= acc_12_V_fu_1556_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_13_V_reg_1049 <= tmp_data_13_V_822_reg_750;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_13_V_reg_1049 <= ap_phi_reg_pp0_iter5_tmp_data_13_V_reg_1049;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_14_V_820_reg_761 <= ap_phi_mux_tmp_data_14_V_phi_fu_1035_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_14_V_820_reg_761 <= 16'd122;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_14_V_reg_1030 <= acc_12_V_fu_1556_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_14_V_reg_1030 <= tmp_data_14_V_820_reg_761;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_14_V_reg_1030 <= ap_phi_reg_pp0_iter5_tmp_data_14_V_reg_1030;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_15_V_818_reg_772 <= ap_phi_mux_tmp_data_15_V_phi_fu_1016_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_15_V_818_reg_772 <= 16'd124;
    end
end

always @ (posedge ap_clk) begin
    if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_15_V_reg_1011 <= tmp_data_15_V_818_reg_772;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_15_V_reg_1011 <= acc_12_V_fu_1556_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_15_V_reg_1011 <= ap_phi_reg_pp0_iter5_tmp_data_15_V_reg_1011;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_1_V_846_reg_618 <= ap_phi_mux_tmp_data_1_V_phi_fu_826_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_1_V_846_reg_618 <= 16'd124;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_1_V_reg_821 <= acc_0_V_fu_1378_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_1_V_reg_821 <= tmp_data_1_V_846_reg_618;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_1_V_reg_821 <= ap_phi_reg_pp0_iter5_tmp_data_1_V_reg_821;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_2_V_844_reg_629 <= ap_phi_mux_tmp_data_2_V_phi_fu_807_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_2_V_844_reg_629 <= 16'd65493;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_2_V_reg_802 <= acc_0_V_fu_1378_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_2_V_reg_802 <= tmp_data_2_V_844_reg_629;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_2_V_reg_802 <= ap_phi_reg_pp0_iter5_tmp_data_2_V_reg_802;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_3_V_842_reg_640 <= ap_phi_mux_tmp_data_3_V_phi_fu_788_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_3_V_842_reg_640 <= 16'd65534;
    end
end

always @ (posedge ap_clk) begin
    if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_3_V_reg_783 <= tmp_data_3_V_842_reg_640;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_3_V_reg_783 <= acc_0_V_fu_1378_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_3_V_reg_783 <= ap_phi_reg_pp0_iter5_tmp_data_3_V_reg_783;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_4_V_840_reg_651 <= ap_phi_mux_tmp_data_4_V_phi_fu_921_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_4_V_840_reg_651 <= 16'd25;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_4_V_reg_916 <= acc_4_V_fu_1435_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_4_V_reg_916 <= tmp_data_4_V_840_reg_651;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_4_V_reg_916 <= ap_phi_reg_pp0_iter5_tmp_data_4_V_reg_916;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_5_V_838_reg_662 <= ap_phi_mux_tmp_data_5_V_phi_fu_902_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_5_V_838_reg_662 <= 16'd65437;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_5_V_reg_897 <= acc_4_V_fu_1435_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_5_V_reg_897 <= tmp_data_5_V_838_reg_662;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_5_V_reg_897 <= ap_phi_reg_pp0_iter5_tmp_data_5_V_reg_897;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_6_V_836_reg_673 <= ap_phi_mux_tmp_data_6_V_phi_fu_883_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_6_V_836_reg_673 <= 16'd65452;
    end
end

always @ (posedge ap_clk) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_6_V_reg_878 <= acc_4_V_fu_1435_p2;
    end else if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_6_V_reg_878 <= tmp_data_6_V_836_reg_673;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_6_V_reg_878 <= ap_phi_reg_pp0_iter5_tmp_data_6_V_reg_878;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_7_V_834_reg_684 <= ap_phi_mux_tmp_data_7_V_phi_fu_864_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_7_V_834_reg_684 <= 16'd65471;
    end
end

always @ (posedge ap_clk) begin
    if ((((out_index_reg_1692_pp0_iter4_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((out_index_reg_1692_pp0_iter4_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_7_V_reg_859 <= tmp_data_7_V_834_reg_684;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_7_V_reg_859 <= acc_4_V_fu_1435_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_7_V_reg_859 <= ap_phi_reg_pp0_iter5_tmp_data_7_V_reg_859;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_8_V_832_reg_695 <= ap_phi_mux_tmp_data_8_V_phi_fu_997_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_8_V_832_reg_695 <= 16'd9;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_8_V_reg_992 <= acc_8_V_fu_1499_p2;
    end else if ((((or_ln_fu_1454_p3 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((or_ln_fu_1454_p3 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_8_V_reg_992 <= tmp_data_8_V_832_reg_695;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_8_V_reg_992 <= ap_phi_reg_pp0_iter5_tmp_data_8_V_reg_992;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_9_V_830_reg_706 <= ap_phi_mux_tmp_data_9_V_phi_fu_978_p8;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_9_V_830_reg_706 <= 16'd65533;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln_fu_1454_p3 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_9_V_reg_973 <= acc_8_V_fu_1499_p2;
    end else if ((((or_ln_fu_1454_p3 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((or_ln_fu_1454_p3 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        tmp_data_9_V_reg_973 <= tmp_data_9_V_830_reg_706;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        tmp_data_9_V_reg_973 <= ap_phi_reg_pp0_iter5_tmp_data_9_V_reg_973;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln151_reg_1688 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index50_reg_584 <= w_index_reg_1673;
    end else if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        w_index50_reg_584 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (icmp_ln49_fu_1566_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        wp_idx51_reg_572 <= i_iw_reg_1633;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        wp_idx51_reg_572 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3))) begin
        i_iw_reg_1633 <= i_iw_fu_1225_p2;
        p_Result_s_reg_1644 <= p_Val2_s_fu_1199_p10[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln151_reg_1688 <= icmp_ln151_fu_1279_p2;
        icmp_ln151_reg_1688_pp0_iter1_reg <= icmp_ln151_reg_1688;
        icmp_ln168_reg_1683 <= icmp_ln168_fu_1273_p2;
        in_index_reg_1678 <= in_index_fu_1267_p2;
        out_index_reg_1692 <= outidx_q0;
        tmp_1155_reg_1699 <= tmp_1155_fu_1289_p5;
        tmp_1156_reg_1709 <= {{w2_V_q0[31:16]}};
        tmp_1157_reg_1714 <= {{w2_V_q0[47:32]}};
        tmp_1158_reg_1719 <= {{w2_V_q0[57:48]}};
        trunc_ln160_1_reg_1704 <= trunc_ln160_1_fu_1298_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln151_reg_1688_pp0_iter2_reg <= icmp_ln151_reg_1688_pp0_iter1_reg;
        icmp_ln151_reg_1688_pp0_iter3_reg <= icmp_ln151_reg_1688_pp0_iter2_reg;
        icmp_ln151_reg_1688_pp0_iter4_reg <= icmp_ln151_reg_1688_pp0_iter3_reg;
        mul_ln1118_1155_reg_1762 <= grp_fu_1578_p2;
        mul_ln1118_1156_reg_1767 <= grp_fu_1584_p2;
        mul_ln1118_1157_reg_1772 <= grp_fu_1590_p2;
        mul_ln1118_reg_1757 <= grp_fu_1572_p2;
        out_index_reg_1692_pp0_iter2_reg <= out_index_reg_1692;
        out_index_reg_1692_pp0_iter3_reg <= out_index_reg_1692_pp0_iter2_reg;
        out_index_reg_1692_pp0_iter4_reg <= out_index_reg_1692_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln20_reg_1614 <= icmp_ln20_fu_1091_p2;
        icmp_ln26_reg_1620 <= icmp_ln26_fu_1097_p2;
        select_ln31_reg_1625 <= select_ln31_fu_1161_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_V_1024_reg_1653 <= data_window_1_V_V_dout;
        tmp_V_1025_reg_1658 <= data_window_2_V_V_dout;
        tmp_V_reg_1648 <= data_window_0_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1673 <= w_index_fu_1261_p2;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln49_fu_1566_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_1688 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_in_index_0_i_i_i_i_i49_phi_fu_599_p4 = select_ln168_fu_1332_p3;
    end else begin
        ap_phi_mux_in_index_0_i_i_i_i_i49_phi_fu_599_p4 = in_index_0_i_i_i_i_i49_reg_595;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd0)) begin
        ap_phi_mux_tmp_data_0_V_phi_fu_845_p8 = acc_0_V_fu_1378_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_0_V_phi_fu_845_p8 = tmp_data_0_V_1148_reg_607;
    end else begin
        ap_phi_mux_tmp_data_0_V_phi_fu_845_p8 = ap_phi_reg_pp0_iter5_tmp_data_0_V_reg_840;
    end
end

always @ (*) begin
    if ((or_ln_fu_1454_p3 == 4'd10)) begin
        ap_phi_mux_tmp_data_10_V_phi_fu_959_p8 = acc_8_V_fu_1499_p2;
    end else if (((or_ln_fu_1454_p3 == 4'd9) | (or_ln_fu_1454_p3 == 4'd8) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8)))) begin
        ap_phi_mux_tmp_data_10_V_phi_fu_959_p8 = tmp_data_10_V_828_reg_717;
    end else begin
        ap_phi_mux_tmp_data_10_V_phi_fu_959_p8 = ap_phi_reg_pp0_iter5_tmp_data_10_V_reg_954;
    end
end

always @ (*) begin
    if (((or_ln_fu_1454_p3 == 4'd10) | (or_ln_fu_1454_p3 == 4'd9) | (or_ln_fu_1454_p3 == 4'd8))) begin
        ap_phi_mux_tmp_data_11_V_phi_fu_940_p8 = tmp_data_11_V_826_reg_728;
    end else if ((~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8))) begin
        ap_phi_mux_tmp_data_11_V_phi_fu_940_p8 = acc_8_V_fu_1499_p2;
    end else begin
        ap_phi_mux_tmp_data_11_V_phi_fu_940_p8 = ap_phi_reg_pp0_iter5_tmp_data_11_V_reg_935;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd0)) begin
        ap_phi_mux_tmp_data_12_V_phi_fu_1073_p8 = acc_12_V_fu_1556_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_12_V_phi_fu_1073_p8 = tmp_data_12_V_824_reg_739;
    end else begin
        ap_phi_mux_tmp_data_12_V_phi_fu_1073_p8 = ap_phi_reg_pp0_iter5_tmp_data_12_V_reg_1068;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd1)) begin
        ap_phi_mux_tmp_data_13_V_phi_fu_1054_p8 = acc_12_V_fu_1556_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_13_V_phi_fu_1054_p8 = tmp_data_13_V_822_reg_750;
    end else begin
        ap_phi_mux_tmp_data_13_V_phi_fu_1054_p8 = ap_phi_reg_pp0_iter5_tmp_data_13_V_reg_1049;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd2)) begin
        ap_phi_mux_tmp_data_14_V_phi_fu_1035_p8 = acc_12_V_fu_1556_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_14_V_phi_fu_1035_p8 = tmp_data_14_V_820_reg_761;
    end else begin
        ap_phi_mux_tmp_data_14_V_phi_fu_1035_p8 = ap_phi_reg_pp0_iter5_tmp_data_14_V_reg_1030;
    end
end

always @ (*) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2))) begin
        ap_phi_mux_tmp_data_15_V_phi_fu_1016_p8 = tmp_data_15_V_818_reg_772;
    end else if ((out_index_reg_1692_pp0_iter4_reg == 2'd3)) begin
        ap_phi_mux_tmp_data_15_V_phi_fu_1016_p8 = acc_12_V_fu_1556_p2;
    end else begin
        ap_phi_mux_tmp_data_15_V_phi_fu_1016_p8 = ap_phi_reg_pp0_iter5_tmp_data_15_V_reg_1011;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd1)) begin
        ap_phi_mux_tmp_data_1_V_phi_fu_826_p8 = acc_0_V_fu_1378_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_1_V_phi_fu_826_p8 = tmp_data_1_V_846_reg_618;
    end else begin
        ap_phi_mux_tmp_data_1_V_phi_fu_826_p8 = ap_phi_reg_pp0_iter5_tmp_data_1_V_reg_821;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd2)) begin
        ap_phi_mux_tmp_data_2_V_phi_fu_807_p8 = acc_0_V_fu_1378_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_2_V_phi_fu_807_p8 = tmp_data_2_V_844_reg_629;
    end else begin
        ap_phi_mux_tmp_data_2_V_phi_fu_807_p8 = ap_phi_reg_pp0_iter5_tmp_data_2_V_reg_802;
    end
end

always @ (*) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2))) begin
        ap_phi_mux_tmp_data_3_V_phi_fu_788_p8 = tmp_data_3_V_842_reg_640;
    end else if ((out_index_reg_1692_pp0_iter4_reg == 2'd3)) begin
        ap_phi_mux_tmp_data_3_V_phi_fu_788_p8 = acc_0_V_fu_1378_p2;
    end else begin
        ap_phi_mux_tmp_data_3_V_phi_fu_788_p8 = ap_phi_reg_pp0_iter5_tmp_data_3_V_reg_783;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd0)) begin
        ap_phi_mux_tmp_data_4_V_phi_fu_921_p8 = acc_4_V_fu_1435_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_4_V_phi_fu_921_p8 = tmp_data_4_V_840_reg_651;
    end else begin
        ap_phi_mux_tmp_data_4_V_phi_fu_921_p8 = ap_phi_reg_pp0_iter5_tmp_data_4_V_reg_916;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd1)) begin
        ap_phi_mux_tmp_data_5_V_phi_fu_902_p8 = acc_4_V_fu_1435_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd2) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_5_V_phi_fu_902_p8 = tmp_data_5_V_838_reg_662;
    end else begin
        ap_phi_mux_tmp_data_5_V_phi_fu_902_p8 = ap_phi_reg_pp0_iter5_tmp_data_5_V_reg_897;
    end
end

always @ (*) begin
    if ((out_index_reg_1692_pp0_iter4_reg == 2'd2)) begin
        ap_phi_mux_tmp_data_6_V_phi_fu_883_p8 = acc_4_V_fu_1435_p2;
    end else if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd3))) begin
        ap_phi_mux_tmp_data_6_V_phi_fu_883_p8 = tmp_data_6_V_836_reg_673;
    end else begin
        ap_phi_mux_tmp_data_6_V_phi_fu_883_p8 = ap_phi_reg_pp0_iter5_tmp_data_6_V_reg_878;
    end
end

always @ (*) begin
    if (((out_index_reg_1692_pp0_iter4_reg == 2'd0) | (out_index_reg_1692_pp0_iter4_reg == 2'd1) | (out_index_reg_1692_pp0_iter4_reg == 2'd2))) begin
        ap_phi_mux_tmp_data_7_V_phi_fu_864_p8 = tmp_data_7_V_834_reg_684;
    end else if ((out_index_reg_1692_pp0_iter4_reg == 2'd3)) begin
        ap_phi_mux_tmp_data_7_V_phi_fu_864_p8 = acc_4_V_fu_1435_p2;
    end else begin
        ap_phi_mux_tmp_data_7_V_phi_fu_864_p8 = ap_phi_reg_pp0_iter5_tmp_data_7_V_reg_859;
    end
end

always @ (*) begin
    if ((or_ln_fu_1454_p3 == 4'd8)) begin
        ap_phi_mux_tmp_data_8_V_phi_fu_997_p8 = acc_8_V_fu_1499_p2;
    end else if (((or_ln_fu_1454_p3 == 4'd10) | (or_ln_fu_1454_p3 == 4'd9) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8)))) begin
        ap_phi_mux_tmp_data_8_V_phi_fu_997_p8 = tmp_data_8_V_832_reg_695;
    end else begin
        ap_phi_mux_tmp_data_8_V_phi_fu_997_p8 = ap_phi_reg_pp0_iter5_tmp_data_8_V_reg_992;
    end
end

always @ (*) begin
    if ((or_ln_fu_1454_p3 == 4'd9)) begin
        ap_phi_mux_tmp_data_9_V_phi_fu_978_p8 = acc_8_V_fu_1499_p2;
    end else if (((or_ln_fu_1454_p3 == 4'd10) | (or_ln_fu_1454_p3 == 4'd8) | (~(or_ln_fu_1454_p3 == 4'd10) & ~(or_ln_fu_1454_p3 == 4'd9) & ~(or_ln_fu_1454_p3 == 4'd8)))) begin
        ap_phi_mux_tmp_data_9_V_phi_fu_978_p8 = tmp_data_9_V_830_reg_706;
    end else begin
        ap_phi_mux_tmp_data_9_V_phi_fu_978_p8 = ap_phi_reg_pp0_iter5_tmp_data_9_V_reg_973;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_1688 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_w_index50_phi_fu_588_p4 = w_index_reg_1673;
    end else begin
        ap_phi_mux_w_index50_phi_fu_588_p4 = w_index50_reg_584;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_V_TDATA_blk_n = data_V_data_V_TVALID_int;
    end else begin
        data_V_data_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_data_V_data_V_U_ack_in == 1'b1) & (data_V_data_V_TVALID == 1'b1))) begin
        data_V_data_V_TREADY = 1'b1;
    end else begin
        data_V_data_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_V_TREADY_int = 1'b1;
    end else begin
        data_V_data_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        data_window_0_V_V_read = 1'b1;
    end else begin
        data_window_0_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln13_fu_1221_p1 == 1'd1))) begin
        data_window_0_V_V_write = 1'b1;
    end else begin
        data_window_0_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        data_window_1_V_V_read = 1'b1;
    end else begin
        data_window_1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3) & (tmp_1320_fu_1231_p3 == 1'd1))) begin
        data_window_1_V_V_write = 1'b1;
    end else begin
        data_window_1_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        data_window_2_V_V_read = 1'b1;
    end else begin
        data_window_2_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3) & (tmp_1321_fu_1239_p3 == 1'd1))) begin
        data_window_2_V_V_write = 1'b1;
    end else begin
        data_window_2_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln49_fu_1566_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_10_V_blk_n = res_V_data_10_V_full_n;
    end else begin
        res_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_10_V_write = 1'b1;
    end else begin
        res_V_data_10_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_11_V_blk_n = res_V_data_11_V_full_n;
    end else begin
        res_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_11_V_write = 1'b1;
    end else begin
        res_V_data_11_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_12_V_blk_n = res_V_data_12_V_full_n;
    end else begin
        res_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_12_V_write = 1'b1;
    end else begin
        res_V_data_12_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_13_V_blk_n = res_V_data_13_V_full_n;
    end else begin
        res_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_13_V_write = 1'b1;
    end else begin
        res_V_data_13_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_14_V_blk_n = res_V_data_14_V_full_n;
    end else begin
        res_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_14_V_write = 1'b1;
    end else begin
        res_V_data_14_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_15_V_blk_n = res_V_data_15_V_full_n;
    end else begin
        res_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_15_V_write = 1'b1;
    end else begin
        res_V_data_15_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n;
    end else begin
        res_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_8_V_write = 1'b1;
    end else begin
        res_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n;
    end else begin
        res_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (p_Result_s_reg_1644 == 1'd1))) begin
        res_V_data_9_V_write = 1'b1;
    end else begin
        res_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (p_Result_s_fu_1247_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if ((~((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1))) & (1'b1 == ap_CS_fsm_state3) & (p_Result_s_fu_1247_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln49_fu_1566_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1)) & (icmp_ln49_fu_1566_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1378_p2 = (trunc_ln_fu_1353_p4 + phi_ln_fu_1365_p6);

assign acc_12_V_fu_1556_p2 = (phi_ln1265_3_fu_1518_p18 + trunc_ln708_1157_fu_1509_p4);

assign acc_4_V_fu_1435_p2 = (phi_ln1265_1_fu_1397_p18 + trunc_ln708_1155_fu_1388_p4);

assign acc_8_V_fu_1499_p2 = (phi_ln1265_2_fu_1461_p18 + trunc_ln708_1156_fu_1445_p4);

assign and_ln26_fu_1174_p2 = (xor_ln20_fu_1169_p2 & icmp_ln26_reg_1620);

assign and_ln31_fu_1149_p2 = (xor_ln26_fu_1143_p2 & icmp_ln31_fu_1119_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11 = ((io_acc_block_signal_op190 == 1'b0) & (p_Result_s_reg_1644 == 1'd1));
end

always @ (*) begin
    ap_block_state3 = ((data_V_data_V_TVALID_int == 1'b0) | ((data_window_2_V_V_full_n == 1'b0) & (tmp_1321_fu_1239_p3 == 1'd1)) | ((data_window_1_V_V_full_n == 1'b0) & (tmp_1320_fu_1231_p3 == 1'd1)) | ((data_window_0_V_V_full_n == 1'b0) & (trunc_ln13_fu_1221_p1 == 1'd1)));
end

always @ (*) begin
    ap_block_state4 = ((data_window_2_V_V_empty_n == 1'b0) | (data_window_1_V_V_empty_n == 1'b0) | (data_window_0_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter5_tmp_data_0_V_reg_840 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_10_V_reg_954 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_11_V_reg_935 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_12_V_reg_1068 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_13_V_reg_1049 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_14_V_reg_1030 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_15_V_reg_1011 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_1_V_reg_821 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_2_V_reg_802 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_3_V_reg_783 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_4_V_reg_916 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_5_V_reg_897 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_6_V_reg_878 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_7_V_reg_859 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_8_V_reg_992 = 'bx;

assign ap_phi_reg_pp0_iter5_tmp_data_9_V_reg_973 = 'bx;

assign ap_ready = internal_ap_ready;

assign grp_fu_1572_p1 = sext_ln1116_cast_fu_1338_p1;

assign grp_fu_1578_p0 = sext_ln1116_cast_fu_1338_p1;

assign grp_fu_1584_p0 = sext_ln1116_cast_fu_1338_p1;

assign grp_fu_1590_p0 = sext_ln1116_cast_fu_1338_p1;

assign i_iw_fu_1225_p2 = (8'd1 + wp_idx51_reg_572);

assign icmp_ln151_fu_1279_p2 = ((ap_phi_mux_w_index50_phi_fu_588_p4 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1273_p2 = (($signed(in_index_fu_1267_p2) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_1091_p2 = ((wp_idx51_reg_572 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_1097_p2 = ((wp_idx51_reg_572 > 8'd198) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_1119_p2 = ((tmp_1319_fu_1109_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_1566_p2 = ((wp_idx51_reg_572 == 8'd199) ? 1'b1 : 1'b0);

assign in_index_fu_1267_p2 = (ap_phi_mux_in_index_0_i_i_i_i_i49_phi_fu_599_p4 + 32'd1);

assign io_acc_block_signal_op190 = (res_V_data_9_V_full_n & res_V_data_8_V_full_n & res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_15_V_full_n & res_V_data_14_V_full_n & res_V_data_13_V_full_n & res_V_data_12_V_full_n & res_V_data_11_V_full_n & res_V_data_10_V_full_n & res_V_data_0_V_full_n);

assign or_ln26_fu_1137_p2 = (icmp_ln26_fu_1097_p2 | icmp_ln20_fu_1091_p2);

assign or_ln321_fu_1187_p2 = (icmp_ln20_reg_1614 | and_ln26_fu_1174_p2);

assign or_ln_fu_1454_p3 = {{2'd2}, {out_index_reg_1692_pp0_iter4_reg}};

assign outidx_address0 = zext_ln155_fu_1255_p1;

assign p_Result_s_fu_1247_p3 = p_Val2_s_fu_1199_p10[32'd2];

assign p_Val2_s_fu_1199_p9 = ((or_ln321_fu_1187_p2[0:0] === 1'b1) ? select_ln321_fu_1179_p3 : select_ln31_reg_1625);

assign phi_ln1265_2_fu_1461_p17 = {{2'd2}, {out_index_reg_1692_pp0_iter4_reg}};

assign r_fu_1103_p2 = ($signed(8'd199) - $signed(wp_idx51_reg_572));

assign res_V_data_0_V_din = tmp_data_0_V_reg_840;

assign res_V_data_10_V_din = tmp_data_10_V_reg_954;

assign res_V_data_11_V_din = tmp_data_11_V_reg_935;

assign res_V_data_12_V_din = tmp_data_12_V_reg_1068;

assign res_V_data_13_V_din = tmp_data_13_V_reg_1049;

assign res_V_data_14_V_din = tmp_data_14_V_reg_1030;

assign res_V_data_15_V_din = tmp_data_15_V_reg_1011;

assign res_V_data_1_V_din = tmp_data_1_V_reg_821;

assign res_V_data_2_V_din = tmp_data_2_V_reg_802;

assign res_V_data_3_V_din = tmp_data_3_V_reg_783;

assign res_V_data_4_V_din = tmp_data_4_V_reg_916;

assign res_V_data_5_V_din = tmp_data_5_V_reg_897;

assign res_V_data_6_V_din = tmp_data_6_V_reg_878;

assign res_V_data_7_V_din = tmp_data_7_V_reg_859;

assign res_V_data_8_V_din = tmp_data_8_V_reg_992;

assign res_V_data_9_V_din = tmp_data_9_V_reg_973;

assign select_ln168_fu_1332_p3 = ((icmp_ln168_reg_1683[0:0] === 1'b1) ? 32'd0 : in_index_reg_1678);

assign select_ln31_fu_1161_p3 = ((and_ln31_fu_1149_p2[0:0] === 1'b1) ? sub_ln31_fu_1155_p2 : select_ln35_fu_1129_p3);

assign select_ln321_fu_1179_p3 = ((and_ln26_fu_1174_p2[0:0] === 1'b1) ? 3'd5 : 3'd0);

assign select_ln35_fu_1129_p3 = ((trunc_ln49_fu_1087_p1[0:0] === 1'b1) ? 3'd1 : 3'd2);

assign sext_ln1116_cast_fu_1338_p1 = $signed(tmp_1155_reg_1699);

assign start_out = real_start;

assign sub_ln31_fu_1155_p2 = ($signed(3'd5) - $signed(trunc_ln32_fu_1125_p1));

assign tmp_1155_fu_1289_p4 = in_index_0_i_i_i_i_i49_reg_595[1:0];

assign tmp_1319_fu_1109_p4 = {{r_fu_1103_p2[7:1]}};

assign tmp_1320_fu_1231_p3 = p_Val2_s_fu_1199_p10[32'd1];

assign tmp_1321_fu_1239_p3 = p_Val2_s_fu_1199_p10[32'd2];

assign trunc_ln13_fu_1221_p1 = p_Val2_s_fu_1199_p10[0:0];

assign trunc_ln160_1_fu_1298_p1 = w2_V_q0[15:0];

assign trunc_ln32_fu_1125_p1 = r_fu_1103_p2[2:0];

assign trunc_ln49_fu_1087_p1 = wp_idx51_reg_572[0:0];

assign trunc_ln708_1155_fu_1388_p4 = {{mul_ln1118_1155_reg_1762[25:10]}};

assign trunc_ln708_1156_fu_1445_p4 = {{mul_ln1118_1156_reg_1767[25:10]}};

assign trunc_ln708_1157_fu_1509_p4 = {{mul_ln1118_1157_reg_1772[25:10]}};

assign trunc_ln_fu_1353_p4 = {{mul_ln1118_reg_1757[25:10]}};

assign w2_V_address0 = zext_ln155_fu_1255_p1;

assign w_index_fu_1261_p2 = (4'd1 + ap_phi_mux_w_index50_phi_fu_588_p4);

assign xor_ln20_fu_1169_p2 = (icmp_ln20_reg_1614 ^ 1'd1);

assign xor_ln26_fu_1143_p2 = (or_ln26_fu_1137_p2 ^ 1'd1);

assign zext_ln1265_fu_1362_p1 = out_index_reg_1692_pp0_iter4_reg;

assign zext_ln155_fu_1255_p1 = ap_phi_mux_w_index50_phi_fu_588_p4;

endmodule //conv_1d_cl_array_array_ap_fixed_16u_config2_s
