# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/steph/Desktop/HLS4ML_NeutDetector/tools/xilinx/Neutrino12/Neutrino12.runs/synth_1/myproject.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/steph/Desktop/HLS4ML_NeutDetector/tools/xilinx/Neutrino12/Neutrino12.cache/wt [current_project]
set_property parent.project_path C:/Users/steph/Desktop/HLS4ML_NeutDetector/tools/xilinx/Neutrino12/Neutrino12.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo c:/Users/steph/Desktop/HLS4ML_NeutDetector/tools/xilinx/Neutrino12/Neutrino12.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_16u_config2_s_outidx_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_32u_config5_s_w5_V_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config12_s_w12_V_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_16u_config4_s_pool_tablbkb_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s_sigmoidEe_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_32u_config7_s_pool_tablcud_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_64u_config8_s_w8_V_rom.dat
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_16u_config2_s_w2_V_rom.dat
}
read_verilog -library xil_defaultlib {
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/Block_proc.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/compute_global_pool_array_array_ap_fixed_64u_config10_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_16u_config2_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_16u_config2_s_outidx.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_16u_config2_s_w2_V.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_32u_config5_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_32u_config5_s_w5_V.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_64u_config8_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/conv_1d_cl_array_array_ap_fixed_64u_config8_s_w8_V.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/dense_array_array_ap_fixed_16_6_5_3_0_1u_config12_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config12_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config12_s_w12_V.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d11_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d11_A_x.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d1_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d23_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d23_A_x.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d3_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d3_A_x.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d49_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d49_A_x.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d99_A.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/fifo_w16_d99_A_x.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/global_pooling1d_cl_array_array_ap_fixed_64u_config10_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mul_mul_16s_10s_26_3_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mul_mul_16s_16s_26_3_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mul_mul_16s_8s_24_3_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_1287_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_164_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_164_5_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_325_9_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_32_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_42_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_646_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_83_16_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject_mux_83_3_1_1.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_16u_config4_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_16u_config4_s_pool_tablbkb.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_32u_config7_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/pooling1d_cl_array_array_ap_fixed_32u_config7_s_pool_tablcud.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/regslice_core.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/relu_array_array_ap_fixed_16u_relu_config3_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/relu_array_array_ap_fixed_32u_relu_config6_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/relu_array_array_ap_fixed_64u_relu_config9_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s_sigmoidEe.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_conv_1d_cl_array_array_ap_fixed_32u_config5_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_conv_1d_cl_array_array_ap_fixed_64u_config8_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_dense_array_array_ap_fixed_16_6_5_3_0_1u_configfYi.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_global_pooling1d_cl_array_array_ap_fixed_64u_coeOg.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_pooling1d_cl_array_array_ap_fixed_16u_config4_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_pooling1d_cl_array_array_ap_fixed_32u_config7_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_relu_array_array_ap_fixed_16u_relu_config3_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_relu_array_array_ap_fixed_32u_relu_config6_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_relu_array_array_ap_fixed_64u_relu_config9_U0.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/start_for_sigmoid_array_array_ap_fixed_1u_sigmoid_config1g8j.v
  C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/uplane_reuse12_implementation/myproject_prj/solution1/impl/verilog/myproject.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/top.xdc
set_property used_in_implementation false [get_files C:/Users/steph/Desktop/HLS4ML_NeutDetector/src/hdl/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top myproject -part xc7vx690tffg1761-2
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef myproject.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file myproject_utilization_synth.rpt -pb myproject_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
