// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_boolean_1 = true;
const bool sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_boolean_0 = false;
const sc_lv<10> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv10_0 = "0000000000";
const sc_lv<32> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv32_4 = "100";
const sc_lv<32> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv32_F = "1111";
const sc_lv<26> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv26_3FFFFF1 = "11111111111111111111110001";
const sc_lv<6> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv6_0 = "000000";
const sc_lv<13> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv13_1 = "1";
const sc_lv<13> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv13_200 = "1000000000";
const sc_lv<32> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv32_C = "1100";
const sc_lv<32> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv32_A = "1010";
const sc_lv<3> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv3_0 = "000";
const sc_lv<10> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv10_200 = "1000000000";
const sc_lv<1> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv1_1 = "1";
const sc_lv<10> sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::ap_const_lv10_3FF = "1111111111";

sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sigmoid_table10_U = new sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s_sigmoidEe("sigmoid_table10_U");
    sigmoid_table10_U->clk(ap_clk);
    sigmoid_table10_U->reset(ap_rst);
    sigmoid_table10_U->address0(sigmoid_table10_address0);
    sigmoid_table10_U->ce0(sigmoid_table10_ce0);
    sigmoid_table10_U->q0(sigmoid_table10_q0);
    regslice_both_res_V_data_V_U = new regslice_both<16>("regslice_both_res_V_data_V_U");
    regslice_both_res_V_data_V_U->ap_clk(ap_clk);
    regslice_both_res_V_data_V_U->ap_rst(ap_rst);
    regslice_both_res_V_data_V_U->data_in(res_V_data_V_TDATA_int);
    regslice_both_res_V_data_V_U->vld_in(res_V_data_V_TVALID_int);
    regslice_both_res_V_data_V_U->ack_in(res_V_data_V_TREADY_int);
    regslice_both_res_V_data_V_U->data_out(res_V_data_V_TDATA);
    regslice_both_res_V_data_V_U->vld_out(regslice_both_res_V_data_V_U_vld_out);
    regslice_both_res_V_data_V_U->ack_out(res_V_data_V_TREADY);
    regslice_both_res_V_data_V_U->apdone_blk(regslice_both_res_V_data_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln106_fu_179_p2);
    sensitive << ( select_ln850_fu_173_p3 );

    SC_METHOD(thread_add_ln700_fu_162_p2);
    sensitive << ( sext_ln850_fu_134_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( regslice_both_res_V_data_V_U_apdone_blk );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( regslice_both_res_V_data_V_U_apdone_blk );
    sensitive << ( res_V_data_V_TREADY_int );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( regslice_both_res_V_data_V_U_apdone_blk );
    sensitive << ( res_V_data_V_TREADY_int );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( data_V_data_V_empty_n );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);
    sensitive << ( regslice_both_res_V_data_V_U_apdone_blk );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_idle_pp0_0to3);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to3 );

    SC_METHOD(thread_data_V_data_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_V_data_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln108_fu_203_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_3_fu_193_p4 );

    SC_METHOD(thread_icmp_ln850_fu_138_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( shl_ln_fu_116_p3 );

    SC_METHOD(thread_icmp_ln851_fu_156_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( p_Result_3_i_i_i_fu_148_p3 );

    SC_METHOD(thread_or_ln107_fu_231_p2);
    sensitive << ( tmp_2_reg_279 );
    sensitive << ( icmp_ln108_reg_285 );

    SC_METHOD(thread_p_Result_3_i_i_i_fu_148_p3);
    sensitive << ( trunc_ln851_fu_144_p1 );

    SC_METHOD(thread_res_V_data_V_TDATA_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( res_V_data_V_TREADY_int );

    SC_METHOD(thread_res_V_data_V_TDATA_int);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sigmoid_table10_q0 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_V_TVALID);
    sensitive << ( regslice_both_res_V_data_V_U_vld_out );

    SC_METHOD(thread_res_V_data_V_TVALID_int);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_select_ln107_1_fu_235_p3);
    sensitive << ( or_ln107_fu_231_p2 );
    sensitive << ( select_ln107_fu_223_p3 );
    sensitive << ( xor_ln106_fu_212_p2 );

    SC_METHOD(thread_select_ln107_fu_223_p3);
    sensitive << ( xor_ln107_fu_218_p2 );

    SC_METHOD(thread_select_ln850_fu_173_p3);
    sensitive << ( sext_ln850_reg_253 );
    sensitive << ( icmp_ln850_reg_259 );
    sensitive << ( select_ln851_fu_168_p3 );

    SC_METHOD(thread_select_ln851_fu_168_p3);
    sensitive << ( sext_ln850_reg_253 );
    sensitive << ( icmp_ln851_reg_264 );
    sensitive << ( add_ln700_reg_269 );

    SC_METHOD(thread_sext_ln850_fu_134_p1);
    sensitive << ( tmp_1_fu_124_p4 );

    SC_METHOD(thread_shl_ln_fu_116_p3);
    sensitive << ( data_V_data_V_dout );

    SC_METHOD(thread_sigmoid_table10_address0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln109_fu_243_p1 );

    SC_METHOD(thread_sigmoid_table10_ce0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_1_fu_124_p4);
    sensitive << ( data_V_data_V_dout );

    SC_METHOD(thread_tmp_3_fu_193_p4);
    sensitive << ( add_ln106_fu_179_p2 );

    SC_METHOD(thread_trunc_ln106_fu_209_p1);
    sensitive << ( select_ln850_reg_274 );

    SC_METHOD(thread_trunc_ln851_fu_144_p1);
    sensitive << ( data_V_data_V_dout );

    SC_METHOD(thread_xor_ln106_fu_212_p2);
    sensitive << ( trunc_ln106_fu_209_p1 );

    SC_METHOD(thread_xor_ln107_fu_218_p2);
    sensitive << ( tmp_2_reg_279 );

    SC_METHOD(thread_zext_ln109_fu_243_p1);
    sensitive << ( select_ln107_1_fu_235_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_V_dout, "(port)data_V_data_V_dout");
    sc_trace(mVcdFile, data_V_data_V_empty_n, "(port)data_V_data_V_empty_n");
    sc_trace(mVcdFile, data_V_data_V_read, "(port)data_V_data_V_read");
    sc_trace(mVcdFile, res_V_data_V_TREADY, "(port)res_V_data_V_TREADY");
    sc_trace(mVcdFile, res_V_data_V_TDATA, "(port)res_V_data_V_TDATA");
    sc_trace(mVcdFile, res_V_data_V_TVALID, "(port)res_V_data_V_TVALID");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, regslice_both_res_V_data_V_U_apdone_blk, "regslice_both_res_V_data_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, sigmoid_table10_address0, "sigmoid_table10_address0");
    sc_trace(mVcdFile, sigmoid_table10_ce0, "sigmoid_table10_ce0");
    sc_trace(mVcdFile, sigmoid_table10_q0, "sigmoid_table10_q0");
    sc_trace(mVcdFile, data_V_data_V_blk_n, "data_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, res_V_data_V_TDATA_blk_n, "res_V_data_V_TDATA_blk_n");
    sc_trace(mVcdFile, sext_ln850_fu_134_p1, "sext_ln850_fu_134_p1");
    sc_trace(mVcdFile, sext_ln850_reg_253, "sext_ln850_reg_253");
    sc_trace(mVcdFile, icmp_ln850_fu_138_p2, "icmp_ln850_fu_138_p2");
    sc_trace(mVcdFile, icmp_ln850_reg_259, "icmp_ln850_reg_259");
    sc_trace(mVcdFile, icmp_ln851_fu_156_p2, "icmp_ln851_fu_156_p2");
    sc_trace(mVcdFile, icmp_ln851_reg_264, "icmp_ln851_reg_264");
    sc_trace(mVcdFile, add_ln700_fu_162_p2, "add_ln700_fu_162_p2");
    sc_trace(mVcdFile, add_ln700_reg_269, "add_ln700_reg_269");
    sc_trace(mVcdFile, select_ln850_fu_173_p3, "select_ln850_fu_173_p3");
    sc_trace(mVcdFile, select_ln850_reg_274, "select_ln850_reg_274");
    sc_trace(mVcdFile, tmp_2_reg_279, "tmp_2_reg_279");
    sc_trace(mVcdFile, icmp_ln108_fu_203_p2, "icmp_ln108_fu_203_p2");
    sc_trace(mVcdFile, icmp_ln108_reg_285, "icmp_ln108_reg_285");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln109_fu_243_p1, "zext_ln109_fu_243_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_1_fu_124_p4, "tmp_1_fu_124_p4");
    sc_trace(mVcdFile, shl_ln_fu_116_p3, "shl_ln_fu_116_p3");
    sc_trace(mVcdFile, trunc_ln851_fu_144_p1, "trunc_ln851_fu_144_p1");
    sc_trace(mVcdFile, p_Result_3_i_i_i_fu_148_p3, "p_Result_3_i_i_i_fu_148_p3");
    sc_trace(mVcdFile, select_ln851_fu_168_p3, "select_ln851_fu_168_p3");
    sc_trace(mVcdFile, add_ln106_fu_179_p2, "add_ln106_fu_179_p2");
    sc_trace(mVcdFile, tmp_3_fu_193_p4, "tmp_3_fu_193_p4");
    sc_trace(mVcdFile, trunc_ln106_fu_209_p1, "trunc_ln106_fu_209_p1");
    sc_trace(mVcdFile, xor_ln107_fu_218_p2, "xor_ln107_fu_218_p2");
    sc_trace(mVcdFile, or_ln107_fu_231_p2, "or_ln107_fu_231_p2");
    sc_trace(mVcdFile, select_ln107_fu_223_p3, "select_ln107_fu_223_p3");
    sc_trace(mVcdFile, xor_ln106_fu_212_p2, "xor_ln106_fu_212_p2");
    sc_trace(mVcdFile, select_ln107_1_fu_235_p3, "select_ln107_1_fu_235_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to3, "ap_idle_pp0_0to3");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, res_V_data_V_TDATA_int, "res_V_data_V_TDATA_int");
    sc_trace(mVcdFile, res_V_data_V_TVALID_int, "res_V_data_V_TVALID_int");
    sc_trace(mVcdFile, res_V_data_V_TREADY_int, "res_V_data_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_res_V_data_V_U_vld_out, "regslice_both_res_V_data_V_U_vld_out");
#endif

    }
}

sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::~sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sigmoid_table10_U;
    delete regslice_both_res_V_data_V_U;
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln700_reg_269 = add_ln700_fu_162_p2.read();
        icmp_ln108_reg_285 = icmp_ln108_fu_203_p2.read();
        icmp_ln850_reg_259 = icmp_ln850_fu_138_p2.read();
        icmp_ln851_reg_264 = icmp_ln851_fu_156_p2.read();
        select_ln850_reg_274 = select_ln850_fu_173_p3.read();
        sext_ln850_reg_253 = sext_ln850_fu_134_p1.read();
        tmp_2_reg_279 = add_ln106_fu_179_p2.read().range(12, 12);
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_add_ln106_fu_179_p2() {
    add_ln106_fu_179_p2 = (!ap_const_lv13_200.is_01() || !select_ln850_fu_173_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_200) + sc_biguint<13>(select_ln850_fu_173_p3.read()));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_add_ln700_fu_162_p2() {
    add_ln700_fu_162_p2 = (!ap_const_lv13_1.is_01() || !sext_ln850_fu_134_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_1) + sc_bigint<13>(sext_ln850_fu_134_p1.read()));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_V_data_V_U_apdone_blk.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_V_data_V_U_apdone_blk.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_TREADY_int.read()))));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()) || 
   esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_V_data_V_U_apdone_blk.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_TREADY_int.read()))));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_V_data_V_U_apdone_blk.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_idle_pp0_0to3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0_0to3 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to3 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to3.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_data_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_V_data_V_blk_n = data_V_data_V_empty_n.read();
    } else {
        data_V_data_V_blk_n = ap_const_logic_1;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_data_V_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_V_read = ap_const_logic_1;
    } else {
        data_V_data_V_read = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_icmp_ln108_fu_203_p2() {
    icmp_ln108_fu_203_p2 = (!tmp_3_fu_193_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_193_p4.read() != ap_const_lv3_0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_icmp_ln850_fu_138_p2() {
    icmp_ln850_fu_138_p2 = (!shl_ln_fu_116_p3.read().is_01() || !ap_const_lv26_3FFFFF1.is_01())? sc_lv<1>(): (sc_bigint<26>(shl_ln_fu_116_p3.read()) < sc_bigint<26>(ap_const_lv26_3FFFFF1));
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_icmp_ln851_fu_156_p2() {
    icmp_ln851_fu_156_p2 = (!p_Result_3_i_i_i_fu_148_p3.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_3_i_i_i_fu_148_p3.read() == ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_or_ln107_fu_231_p2() {
    or_ln107_fu_231_p2 = (tmp_2_reg_279.read() | icmp_ln108_reg_285.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_p_Result_3_i_i_i_fu_148_p3() {
    p_Result_3_i_i_i_fu_148_p3 = esl_concat<4,6>(trunc_ln851_fu_144_p1.read(), ap_const_lv6_0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_res_V_data_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)))) {
        res_V_data_V_TDATA_blk_n = res_V_data_V_TREADY_int.read();
    } else {
        res_V_data_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_res_V_data_V_TDATA_int() {
    res_V_data_V_TDATA_int = esl_zext<16,10>(sigmoid_table10_q0.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_res_V_data_V_TVALID() {
    res_V_data_V_TVALID = regslice_both_res_V_data_V_U_vld_out.read();
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_res_V_data_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_V_TVALID_int = ap_const_logic_1;
    } else {
        res_V_data_V_TVALID_int = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_select_ln107_1_fu_235_p3() {
    select_ln107_1_fu_235_p3 = (!or_ln107_fu_231_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln107_fu_231_p2.read()[0].to_bool())? select_ln107_fu_223_p3.read(): xor_ln106_fu_212_p2.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_select_ln107_fu_223_p3() {
    select_ln107_fu_223_p3 = (!xor_ln107_fu_218_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln107_fu_218_p2.read()[0].to_bool())? ap_const_lv10_3FF: ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_select_ln850_fu_173_p3() {
    select_ln850_fu_173_p3 = (!icmp_ln850_reg_259.read()[0].is_01())? sc_lv<13>(): ((icmp_ln850_reg_259.read()[0].to_bool())? select_ln851_fu_168_p3.read(): sext_ln850_reg_253.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_select_ln851_fu_168_p3() {
    select_ln851_fu_168_p3 = (!icmp_ln851_reg_264.read()[0].is_01())? sc_lv<13>(): ((icmp_ln851_reg_264.read()[0].to_bool())? sext_ln850_reg_253.read(): add_ln700_reg_269.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_sext_ln850_fu_134_p1() {
    sext_ln850_fu_134_p1 = esl_sext<13,12>(tmp_1_fu_124_p4.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_shl_ln_fu_116_p3() {
    shl_ln_fu_116_p3 = esl_concat<16,10>(data_V_data_V_dout.read(), ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_sigmoid_table10_address0() {
    sigmoid_table10_address0 =  (sc_lv<10>) (zext_ln109_fu_243_p1.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_sigmoid_table10_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        sigmoid_table10_ce0 = ap_const_logic_1;
    } else {
        sigmoid_table10_ce0 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_tmp_1_fu_124_p4() {
    tmp_1_fu_124_p4 = data_V_data_V_dout.read().range(15, 4);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_tmp_3_fu_193_p4() {
    tmp_3_fu_193_p4 = add_ln106_fu_179_p2.read().range(12, 10);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_trunc_ln106_fu_209_p1() {
    trunc_ln106_fu_209_p1 = select_ln850_reg_274.read().range(10-1, 0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_trunc_ln851_fu_144_p1() {
    trunc_ln851_fu_144_p1 = data_V_data_V_dout.read().range(4-1, 0);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_xor_ln106_fu_212_p2() {
    xor_ln106_fu_212_p2 = (trunc_ln106_fu_209_p1.read() ^ ap_const_lv10_200);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_xor_ln107_fu_218_p2() {
    xor_ln107_fu_218_p2 = (tmp_2_reg_279.read() ^ ap_const_lv1_1);
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_zext_ln109_fu_243_p1() {
    zext_ln109_fu_243_p1 = esl_zext<64,10>(select_ln107_1_fu_235_p3.read());
}

void sigmoid_array_array_ap_fixed_1u_sigmoid_config13_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

